#write a program to input 8 numbers from the user and display all the unique numbers
n= int(input("Enter number 1 :"))
n1= int(input("Enter number 2 :"))
n2= int(input("Enter number 3 :"))
n3= int(input("Enter number 4 :"))
n4= int(input("Enter number 5 :"))
n5= int(input("Enter number 6:"))
n6= int(input("Enter number 7 :"))
n7= int(input("Enter number 8 :"))
unique_numbers = {n, n1, n2, n3, n4, n5, n6, n7}
print("The unique numbers are:", unique_numbers)
